services:
  mdbook:
    container_name: documentacionYoltla
    image: peaceiris/mdbook:latest
    stdin_open: true
    tty: true
    ports:
      - 3034:3000
      - 3001:3001
    volumes:
      - ${PWD}:/book
    command:
      - serve
      - --hostname
      - '0.0.0.0'
